import { useState } from 'react';
import { Search, FileCode2, FileText, Download, History, Eye, ArrowRightLeft, FolderOpen, Code2, Beaker, CheckCircle2 } from 'lucide-react';

export default function Artifacts() {
  const [selectedArtifact, setSelectedArtifact] = useState<number | null>(0);
  
  const artifacts = [
    { name: "architecture.md", type: "markdown", icon: FileText, size: "12 KB", author: "Technical Architect", time: "2 hours ago", status: "Approved" },
    { name: "player.gd", type: "gdscript", icon: FileCode2, size: "4.2 KB", author: "Gameplay Engineer", time: "1 hour ago", status: "Approved" },
    { name: "enemy.gd", type: "gdscript", icon: FileCode2, size: "8.5 KB", author: "Gameplay Engineer", time: "1 hour ago", status: "Approved" },
    { name: "balance.md", type: "markdown", icon: FileText, size: "2.1 KB", author: "QA & Balance", time: "45 mins ago", status: "Approved" },
    { name: "review.md", type: "markdown", icon: FileText, size: "3.4 KB", author: "Executive Reviewer", time: "30 mins ago", status: "Pending Merge" }
  ];

  const dummyCode = `extends CharacterBody3D

const SPEED = 5.0
const JUMP_VELOCITY = 4.5

# Get the gravity from the project settings to be synced with RigidBody nodes.
var gravity = ProjectSettings.get_setting("physics/3d/default_gravity")

func _physics_process(delta):
\t# Add the gravity.
\tif not is_on_floor():
\t\tvelocity.y -= gravity * delta

\t# Handle jump.
\tif Input.is_action_just_pressed("ui_accept") and is_on_floor():
\t\tvelocity.y = JUMP_VELOCITY

\t# Get the input direction and handle the movement/deceleration.
\tvar input_dir = Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
\tvar direction = (transform.basis * Vector3(input_dir.x, 0, input_dir.y)).normalized()
\tif direction:
\t\tvelocity.x = direction.x * SPEED
\t\tvelocity.z = direction.z * SPEED
\telse:
\t\tvelocity.x = move_toward(velocity.x, 0, SPEED)
\t\tvelocity.z = move_toward(velocity.z, 0, SPEED)

\tmove_and_slide()
`;

  return (
    <div style={{ gridColumn: '2 / -1', gridRow: '1 / -1', display: 'flex', flexDirection: 'column', height: '100%', background: 'var(--bg-primary)', position: 'relative' }}>
      {/* COMING SOON OVERLAY */}
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.8)', zIndex: 100, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', backdropFilter: 'blur(4px)' }}>
        <h2 style={{ fontSize: '32px', color: 'var(--text-primary)', marginBottom: '16px' }}>Work In Progress</h2>
        <p style={{ color: 'var(--text-secondary)', fontSize: '16px', maxWidth: '400px', textAlign: 'center', lineHeight: '1.5' }}>This tab is a visual mockup for the SwarmCircuit vision. We are currently focusing backend development on the core Workspace Execution Graph and Memory Systems.</p>
      </div>

      
      {/* Top Header */}
      <header style={{ padding: '24px 32px', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 style={{ fontSize: '20px', fontWeight: 600, color: 'var(--text-primary)' }}>Artifact Explorer</h1>
          <div style={{ fontSize: '13px', color: 'var(--text-muted)', marginTop: '4px' }}>Browse, preview, and review code and documents generated by the swarm.</div>
        </div>
      </header>

      <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
        
        {/* Artifact List Sidebar */}
        <div style={{ width: '320px', borderRight: '1px solid var(--border-color)', background: 'var(--bg-secondary)', overflowY: 'auto' }}>
          
          <div style={{ padding: '16px', borderBottom: '1px solid var(--border-color)' }}>
            <div style={{ display: 'flex', alignItems: 'center', background: 'var(--bg-primary)', border: '1px solid var(--border-color)', borderRadius: '6px', padding: '8px 12px' }}>
              <Search size={14} color="var(--text-muted)" style={{ marginRight: '8px' }} />
              <input type="text" placeholder="Search artifacts..." style={{ background: 'transparent', border: 'none', color: 'var(--text-primary)', width: '100%', outline: 'none', fontSize: '12px' }} />
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column' }}>
            {artifacts.map((file, i) => {
              const isActive = selectedArtifact === i;
              return (
                <div key={i} onClick={() => setSelectedArtifact(i)} style={{ 
                  padding: '16px', borderBottom: '1px solid var(--border-color)', cursor: 'pointer',
                  background: isActive ? 'var(--bg-tertiary)' : 'transparent',
                  borderLeft: `3px solid ${isActive ? 'var(--accent-color)' : 'transparent'}`
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                    <file.icon size={16} color={isActive ? "var(--accent-color)" : "var(--text-secondary)"} />
                    <div style={{ fontSize: '14px', fontWeight: 500, color: isActive ? 'var(--text-primary)' : 'var(--text-secondary)' }}>{file.name}</div>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '11px', color: 'var(--text-muted)' }}>
                    <span>{file.author}</span>
                    <span>{file.time}</span>
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        {/* Artifact Details Panel */}
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
          
          {selectedArtifact !== null ? (
            <>
              {/* Toolbar */}
              <div style={{ padding: '16px 24px', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'var(--bg-tertiary)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                  <div style={{ fontSize: '15px', fontWeight: 600, color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    {artifacts[selectedArtifact].name}
                  </div>
                  <div style={{ fontSize: '11px', color: 'var(--status-completed)', fontWeight: 600, background: 'rgba(23, 201, 100, 0.1)', padding: '4px 8px', borderRadius: '4px', display: 'flex', alignItems: 'center', gap: '4px' }}>
                    <CheckCircle2 size={12} /> {artifacts[selectedArtifact].status}
                  </div>
                </div>
                
                <div style={{ display: 'flex', gap: '8px' }}>
                  <button style={{ background: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)', padding: '6px 12px', borderRadius: '6px', fontSize: '12px', fontWeight: 500, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <Eye size={14} /> Preview
                  </button>
                  <button style={{ background: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)', padding: '6px 12px', borderRadius: '6px', fontSize: '12px', fontWeight: 500, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <ArrowRightLeft size={14} /> View Diff
                  </button>
                  <button style={{ background: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)', padding: '6px 12px', borderRadius: '6px', fontSize: '12px', fontWeight: 500, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <History size={14} /> History
                  </button>
                  <button style={{ background: 'var(--accent-color)', border: 'none', color: '#000', padding: '6px 12px', borderRadius: '6px', fontSize: '12px', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', marginLeft: '8px' }}>
                    <Download size={14} /> Download
                  </button>
                </div>
              </div>

              {/* Code Viewer */}
              <div style={{ flex: 1, padding: '24px', overflowY: 'auto', background: '#0a0a0a' }}>
                <pre style={{ margin: 0, fontFamily: 'monospace', fontSize: '13px', color: '#e0e0e0', lineHeight: 1.6 }}>
                  {artifacts[selectedArtifact].type === 'gdscript' ? dummyCode : 
`# Architecture Document

## Overview
This document outlines the proposed changes to the player controller architecture...

## Node Hierarchy
- Player (CharacterBody3D)
  - CollisionShape3D
  - MeshInstance3D
  - Camera3D
`}
                </pre>
              </div>
            </>
          ) : (
            <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)', fontSize: '14px' }}>
              Select an artifact to view its contents.
            </div>
          )}

        </div>
      </div>
    </div>
  );
}
